'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''TxtCurrUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCurrUser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtAcctNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAcctNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHolder As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtBranchCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBranchCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBranch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDTransType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDTransType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtInstruNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInstruNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtTransDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDCrDr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDCrDr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtParticular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtParticular As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtTransAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDCashAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDCashAcct As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CheckClearChq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckClearChq As Global.System.Web.UI.WebControls.CheckBox
End Class
